Tinka
Relinks/omnipay-buckaroo pull request #4
Opened 2020-10-28 11:12 UTC by nkop

2020-10-28 14:28 UTC, jarricvankrieken approved these changes

2020-10-28 14:28 UTC, jarricvankrieken commented on src/Message/PurchaseRequest.php
> +                    $selectableServices = $this->getSiteId() == 7
waarom geen constant meer?

2020-10-28 14:29 UTC, jarricvankrieken requested changes
.

2020-10-29 08:16 UTC, nkop commented on src/Message/PurchaseRequest.php
> +                    $selectableServices = $this->getSiteId() == 7
Die  constant bestaat niet in deze package

2020-11-17 07:42 UTC, kvdv approved these changes

2020-11-17 07:44 UTC, merged