Klarna
Relinks/omnipay-buckaroo pull request #5
Opened 2020-12-18 11:28 UTC by Harm-Joost

FIN-234

2020-12-23 12:37 UTC, nkop commented on src/Message/DataRequest.php
> +        } elseif ($this->getPaymentMethod() =='klarnakp') {
```suggestion
        } elseif ($this->getPaymentMethod() == 'klarnakp') {
```

2020-12-23 12:45 UTC, nkop submitted a review, later dismissed
lgtm

2021-01-05 09:11 UTC, Harm-Joost commented
FIN-235 also added to this branch

2021-01-05 09:45 UTC, nkop requested changes

2021-01-05 09:45 UTC, nkop commented on src/Message/CancelReservationRequest.php
> +namespace Omnipay\Buckaroo\Message;
hier moeten whitelines tussen

2021-01-05 09:45 UTC, nkop commented on src/Message/CancelReservationRequest.php
> + * Currently only used for klarnakp (nieuwe klarna paymethod)
```suggestion
 * Currently only used for klarnakp
```

2021-01-05 09:45 UTC, nkop commented on src/Message/CancelReservationRequest.php
> +                ['Name' => $this->getPaymentMethod(),
ik zou een enter na de [ doen

2021-01-05 09:45 UTC, nkop commented on src/Message/CancelReservationResponse.php
> +namespace Omnipay\Buckaroo\Message;
whitelines ertussen

2021-01-05 09:48 UTC, Harm-Joost commented on src/Message/CancelReservationRequest.php
> +namespace Omnipay\Buckaroo\Message;
tussen php en declare staat zelden een whiteline in buckaroo 🤔

2021-01-26 10:00 UTC, nkop approved these changes

2021-01-26 10:26 UTC, nkop approved these changes

2021-01-26 10:26 UTC, merged